### ISSUE TITLE
Bot for autoupdate

### ISSUE THREAD

**Issue by jeanbispo** [gideaoms/clark-orm#2]
A good idea is to configure a bot to automatically open PR's as soon as there is an update from lucid, as soon as I have time I will try to develop this idea.

Congratulations on the project haha, I was in a huge effort doing everything manually here as knex and I found this mention of the project: https://github.com/adonisjs/lucid/issues/695#issuecomment-881770294

**Comment by gideaoms** [comment]
Thanks, man.
Yep, great idea, send me a PR and I will approve it.
In fact, Lucid is a great ORM, but unfortunately, it works only in the Adonis ecosystem.
